test_format = 1.0

[default]

    # ------------
    # Tests to run
    # ------------

    exclude = ["install.multi", "install.private", "change_url"]
    # The test IDs to be used in only/exclude statements are: install.root, install.subdir, install.nourl, install.multi, backup_restore, upgrade, upgrade.someCommitId change_url

    # -------------------------------
    # Default args to use for install
    # -------------------------------

    # Nothing to do here...yet

    # -------------------------------
    # Commits to test upgrade from
    # -------------------------------

    test_upgrade_from.e6e04a0.name = "Upgrade from 2024.02.18~ynh1"
    test_upgrade_from.e6e04a0.args.domain="domain.tld"
    test_upgrade_from.e6e04a0.args.is_public=1
    test_upgrade_from.e6e04a0.args.admin="john"
    test_upgrade_from.e6e04a0.args.language="fr_FR"
